language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  # Build Docker container and push to Docker Hub
  provider: script
  script: bash deploy.sh
  on:
    branch: develop